#!/bin/bash


case ${1} in 
	start)
		/usr/bin/python3 /userdata/system/noctua/noctua-fan-control.py &
		PID=$!
		echo $PID > /userdata/system/services/noctua-service.pid
		;;
	stop)
		PID=`cat /userdata/system/services/noctua-service.pid`
		kill -s SIGTERM $PID
		rm /userdata/system/services/noctua-service.pid 
		;;
esac
